### ISSUE TITLE
Overriding of default styles (css).

### ISSUE THREAD

**Issue by lompy** [jipiboily/monologue#113]
When creating `app/assets/stylesheets/monologue/blog/custom.css` contents of this file indeed go to the final style sheet, but they appear in the file not in the end. This way `custom.css` itself is being overrided by defaults. Solved it by changing one line in the gem:

<pre>
app/assets/stylesheets/monologue/blog/application.css: line 12
        
-        *= require monologue/blog/custom
+        *= include monologue/blog/custom`
</pre>

I'm using monologue 0.2.0 with rails 3.2.8. But with the proposed solution `custom.css` appears twice. Something is needed to be done with `*= require_tree .` in `application.css`.

**Comment by kacyhulme** [comment]
I added a custom.css inside app/assets/stylesheets/monologue/blog and it works perfectly in development. But changes are not showing in production. Anything else I need to do other than add the custom.css file? Should I copy over Monologue's application.css?
