### ISSUE TITLE
nice to have with mongoid

### ISSUE THREAD

**Issue by sergey-alekseev** [jipiboily/monologue#133]
now ActionController::RoutingError - uninitialized constant ActiveRecord:
when accessing /blog

**Comment by gagoit** [comment]
Hi all, I very like this gem and have applied to my mongoid application. I also converted this gem for supporting mongoid. You can check out my updated gem [here](https://github.com/gagoit/monologue/blob). I also write an [example application](https://github.com/gagoit/monologue-mongoid-rails4-example) with the [demo](http://monologue-mongoid-rails4.herokuapp.com/blog/monologue/login). Admin account: monologue@example.com / monologue

**Comment by jipiboily** [comment]
:+1: :heart:
