### ISSUE TITLE
Twitter feed not working

### ISSUE THREAD

**Issue by serialbandicoot** [jipiboily/monologue#137]
I noticed the twitter feed was not working and after some searching it looks like the _latest_tweets partial needs updating.

I've replaced this:
http://twitter.com/statuses/user_timeline
with:
https://api.twitter.com/1/statuses/user_timeline

And this seemed to fix it. Do you want me to create a pull request? I'll just use deface for the moment.

BTW: Great gem keep up the good work.

**Comment by RWSDev** [comment]
Newest solution:
if anyone wants to add twitter support just replace:
`<script type="text/javascript" src="https://api.twitter.com/1/statuses/user_timeline/<%= Monologue::Config.twitter_username %>.json?callback=TwitterWidget.callback&amp;count=5"></script>
`
with:
`<a class="twitter-timeline" data-tweet-limit="3" href="https://twitter.com/<%= Monologue::Config.twitter_username %>">Tweets by <%= Monologue::Config.twitter_username %></a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`
