### ISSUE TITLE
noobie rails dev here

### ISSUE THREAD

**Issue by OxenBoxen** [jipiboily/monologue#141]
I have been following the installation instructions, but I am inexperienced with adding engines to existing rails apps. I have run the command line - bundle exec rake monologue:install:migrations & bundle exec rake db:migrate and everything seems to be fine. however, I dont have config/initializers/monologue.rb or any of the monologue controllers, models, etc. Will they not show up if I am trying to add monologue as an engine?  I know monologue is installed because I can get to http://localhost:3000/monologue just fine and write up articles. Sorry for the noobish question, just trying to get it set up correctly thanks!

**Comment by anandjacob87** [comment]
can somebody post step by step procedure to make  monologue work.
