### ISSUE TITLE
initializers/monologue.rb - undefined method `config' for Monologue:Module

### ISSUE THREAD

**Issue by mhenke** [jipiboily/monologue#173]
=> Booting Thin
=> Rails 3.2.14 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/home/mhenke/rails_projects/innovateomaha/config/initializers/monologue.rb:1:in `<top (required)>': undefined method`config' for Monologue:Module (NoMethodError)

https://github.com/jipiboily/monologue/blob/master/spec/dummy/config/initializers/monologue.rb

**Comment by pollyking** [comment]
I'm getting this error when I try push my Rails 4/Monologue app to Heroku, works fine locally though..

**Comment by travisdmathis** [comment]
getting this error when trying to push to AWS w/ capistrano 3.. Works locally
