### ISSUE TITLE
CKEditor not showing up in production

### ISSUE THREAD

**Issue by msevestre** [jipiboily/monologue#199]
Using Rails 4.0.5 and Monologue 0.4.0
The icons on the blog editor provided by CKEditor are not visible in production. Everything works fine in development.

This is due to a problem with the asset pipeline. More precisely, the file 'icons.png' is for some reason still referenced from the editor using its default file name and is not the using the one served by the asset pipeline.

A quick fix was to copy the file icons.png under assets/ckeditor/skins/moono/ but I am wondering if I need to set some specific options to avoid this hack.

@abreckner: any idea?

**Comment by jipiboily** [comment]
Closing this for now, but might have to fix it during #314

**Comment by abreckner** [comment]
Sorry @msevestre, I only just saw this now.

I ended up using the CDN version of CKEditor on the project I was using in order to get around this...

(No longer working on that project I am afraid).

Thanks
