### ISSUE TITLE
Reporting missing blog entries

### ISSUE THREAD

**Issue by dept42** [jipiboily/monologue#228]
This isn't really a bug/feature, so much as something that might be helpful to put in the documentation somewhere.

I migrated to Monologue from another blog, and wanted to make sure to catch if people were being linked to something that was now missing. However, the post-not-found handling in Monologue doesn't bubble up the Rack stack and show up in default error reporting like not-found pages in the main app. To report missing Monologue pages, I added the following to my initializer:

``` ruby
Rails.application.config.to_prepare do
  Monologue::ApplicationController.class_eval do
    def not_found_with_rollbar
      Rollbar.warning('Blog post not found')
      not_found_without_rollbar
    end
    alias_method_chain :not_found, :rollbar
  end
end
```

I suspect there might be a way to adjust Monologue so that this wasn't necessary, by doing some Rack magic to indicate "nothing found here" instead of rendering the not-found page -- but at a minimum, I thought the above might be helpful to others.

**Comment by msevestre** [comment]
thanks for the info. Can you create a gist with the code and your explanation and i could link the documentation to it?
