### ISSUE TITLE
bin/rake monologue:install:migrations throws an error

### ISSUE THREAD

**Issue by TheGreatDeVane** [jipiboily/monologue#232]
I'm trying to add monologue but every time I run bin/rake monologue:install:migrations I get the following error.

/Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:238:in `add_request_method': You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action" (ArgumentError)
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:124:in `initialize'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:78:in `new'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:78:in `build'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1559:in `add_route'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1536:in `decomposed_match'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1507:in `each'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1507:in `match'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/monologue-0.2.0/config/routes.rb:3:in `block in <top (required)>'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:601:in `instance_exec'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:601:in `block in with_default_scope'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:600:in `with_default_scope'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:421:in `eval_block'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:401:in `draw'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/monologue-0.2.0/config/routes.rb:1:in `<top (required)>'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /Users/Andy/Desktop/Programs/railsgirls/config/environment.rb:5:in `<top (required)>'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:92:in `preload'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Andy/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by msevestre** [comment]
What version of rails are you using?

**Comment by TheGreatDeVane** [comment]
> what version of rails are you using?
I'm running 4.2.0

**Comment by jipiboily** [comment]
I think `match` was deprecated in 4.1 and removed in 4.2...?

**Comment by pollyking** [comment]
I'm having the same issue but only when I push to heroku, not locally, any ideas?

**Comment by Mufc2202** [comment]
I am having the same issue. Anyone know how to resolve it?

**Comment by pollyking** [comment]
Are you using Rails 4?

**Comment by Mufc2202** [comment]
Yes. I am using Rails 4.2.0 and Ruby 2.2.0

**Comment by pollyking** [comment]
I don't think it works with 4.. just from reading past issues.

**Comment by Mufc2202** [comment]
I have gotten that impression from the forums as well.

**Comment by jipiboily** [comment]
It should work with Rails 4 AFAIK, but not sure it was tested with 4.1, and 4.2 is quite unlikely.

Might be worth moving this discussion to https://github.com/jipiboily/monologue/issues/233?

**Comment by pollyking** [comment]
I was thinking after that I might have had it going in 4.2 locally but could not push to Herroku. 


Sent on the go with Vodafone

<div>-------- Original message --------</div><div>From: Jean-Philippe Boily <notifications@github.com> </div><div>Date:11/02/2015  9:26 AM  (GMT+08:00) </div><div>To: jipiboily/monologue <monologue@noreply.github.com> </div><div>Cc: pollylangford <lauren_l@outlook.com> </div><div>Subject: Re: [monologue] bin/rake monologue:install:migrations throws an error
  (#232) </div><div>
</div>It should work with Rails 4 AFAIK, but not sure it was tested with 4.1, and 4.2 is quite unlikely.

Might be worth moving this discussion to #233?

**Comment by ThomasTheFourth** [comment]
You need to grab the latest in your gem file:
gem 'monologue', github: 'jipiboily/monologue'

That fixed the error above for me, but I still had gem dependency version issues, so I had to fork and update the Gem spec, if you have those, the fork is here:
gem 'monologue', github: 'ThomasTheFourth/monologue'

**Comment by kyle-annen** [comment]
Thanks Thomas, I used your fork and it works great!

**Comment by msevestre** [comment]
Can you submit a PR for that and I can merge it?

**Comment by kyle-annen** [comment]
Submitted

**Comment by msevestre** [comment]
fixed. Thanks
