### ISSUE TITLE
Rails 4.2.0 compatible

### ISSUE THREAD

**Issue by mattherick** [jipiboily/monologue#233]
Hi!

Is this gem already rails 4.2 compatible?

My Gemfile:
   
    gem "rails", "4.2.0"
    gem 'monologue', :git => "git://github.com/jipiboily/monologue", :branch => "master"

if I try to  install the bundle I get following error:

    Fetching git://github.com/jipiboily/monologue
    Fetching gem metadata from https://rubygems.org/.........
    Fetching additional metadata from https://rubygems.org/..
    Resolving dependencies...
    Bundler could not find compatible versions for gem "sass-rails":
      In Gemfile:
        monologue (>= 0) ruby depends on
          sass-rails (~> 4.0.0) ruby

        sass-rails (5.0.1)

I can see the dependencies in the monologue.gemspec file:

    s.add_dependency "rails", ">= 4.0.4"
    s.add_dependency "sass-rails",'~> 4.0.0'

Could this simple be updated to rails 4.2 or will such an update cause spec failures? Did you try it out already?

**Comment by jipiboily** [comment]
I didn't try it myself but I am not expecting any major problems, updating the gemspec should cover that to start with.

**Comment by jipiboily** [comment]
Oh, and PR welcomed.

**Comment by StevenNunez** [comment]
Rails also removes controller level `respond_to` calls in 4.2
![image](https://cloud.githubusercontent.com/assets/325485/6827642/028c52a4-d2df-11e4-88f4-c6ddd3228a6c.png)

**Comment by msevestre** [comment]
This should now be fixed. Please give it a shot and let me know if you still have issues
