### ISSUE TITLE
Cannot Setup or Migrate Databases

### ISSUE THREAD

**Issue by pollyking** [jipiboily/monologue#235]
Hi, not sure what I'm doing wrong, I really want to use Monologue as my blogging engine but when I run heroku run bundle exec rake db:setup i get this error: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege. When I run: heroku run bundle exec rake db:migrate I get this error: NameError: uninitialized constant Monologue. Is this normal? Thanks in advance.

**Comment by msevestre** [comment]
Did you search for similar issues on Google?
http://stackoverflow.com/questions/20293895/rails-4-0-1-on-heroku-cant-create-database

This is a heroku configuration issue more than anything I would say

**Comment by msevestre** [comment]
https://devcenter.heroku.com/articles/postgres-logs-errors

Might help as well

**Comment by pollyking** [comment]
Thanks, I think you might be right. I've checked all of the credentials and they are correct.. I'll keep looking. Thanks for the response. :)

**Comment by jipiboily** [comment]
This is indeed Heroku specific. 95%+ sure :)

I use Heroku extensively, so if you want to paste the exact steps you used here to setup the app, database and Monologue, maybe I'll see what happened.

**Comment by pollyking** [comment]
My bad I was using Rails 4 and sass-rails 5.0 I think the error stemmed from there?
