### ISSUE TITLE
i18n entry missing: en.monologue.admin.posts.index.author

### ISSUE THREAD

**Issue by weedySeaDragon** [jipiboily/monologue#241]
I just installed monologue and went to the administration page `[monologue root]/monologue` which is loading the template  `/views/monologue/admin/posts/index.html.erb ` .  Got an error message reporting that an i18n entry is missing:

`I18n::MissingTranslationData - translation missing: en.monologue.admin.posts.index.author:`

I added the entry (just used the value "author") and it worked just fine.
It's a simple fix, but it seems odd to me that no one else has reported this error.

**Comment by jipiboily** [comment]
In which language? Can you create a PR fixing it?

**Comment by weedySeaDragon** [comment]
It happened in English.  But I didn't see an entry for French, either.  (Didn't look explicitly at other languages.)
I can try to create a  PR in a day or two. (A little overloaded, but will try.)
