### ISSUE TITLE
Is there a blog on production that I can see?

### ISSUE THREAD

**Issue by marvindanig** [jipiboily/monologue#249]
It'd be nice to have links to few live and important blogs that are using monologue. I am looking for a ready made low/zero maintenance solution in Rails 4.2. Some good designs and demos would help people like me make up their mind.

Just a suggestion. Thanks for the gem though!

**Comment by jipiboily** [comment]
It might not be up to date, but you can find such a list here https://github.com/jipiboily/monologue/wiki/Sites-running-Monologue :)

I know @msevestre used it multiple projects too and many other people...but I don't know for which projects :)

**Comment by marvindanig** [comment]
Thanks! Yeah that list needs an update. I'm closing this issue for now.
