### ISSUE TITLE
Sidebar not visible?

### ISSUE THREAD

**Issue by johncox00** [jipiboily/monologue#255]
Got monologue running locally, but the config for the sidebar doesn't make it show up. Am I missing something?
```
Monologue.config do |config|
...
  config.sidebar = ["latest_posts", "categories", "tag_cloud"]
...
end
```

**Comment by msevestre** [comment]
What do you see on the homepage?
Can you add a blog post?

**Comment by johncox00** [comment]
Can't see it on the home page, but I can add posts, comments, etc. When I inspect the source of the page, there are no divs present that would indicate that they would have content pertinent to the sidebar. Is there some minimum number of posts that have to be present before it shows up?

**Comment by msevestre** [comment]
Where is this code located?
looking at the code
https://github.com/jipiboily/monologue/blob/master/app/views/layouts/monologue/application/_sidebar.html.erb#L1

the side bar should be visible if Monologue::Config.sidebar is set.

**Comment by msevestre** [comment]
can you share you repo on github so that I can have a look?

**Comment by johncox00** [comment]
Sure. I'll add you to it. Stand by.

On Fri, Apr 24, 2015 at 1:23 PM, Michael Sevestre <notifications@github.com>
wrote:

> can you share you repo on github so that I can have a look?
>
>
> On Fri, Apr 24, 2015 at 3:22 PM, Michael Sevestre <
> michael.sevestre@gmail.com> wrote:
>
> > Where is this code located?
> > looking at the code
> >
> >
> https://github.com/jipiboily/monologue/blob/master/app/views/layouts/monologue/application/_sidebar.html.erb#L1
> >
> > the side bar should be visible if Monologue::Config.sidebar is set.
> >
> > On Fri, Apr 24, 2015 at 3:12 PM, John Cox <notifications@github.com>
> > wrote:
> >
> >> Can't see it on the home page, but I can add posts, comments, etc. When
> I
> >> inspect the source of the page, there are no divs present that would
> >> indicate that they would have content pertinent to the sidebar. Is there
> >> some minimum number of posts that have to be present before it shows up?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/jipiboily/monologue/issues/255#issuecomment-96039216>
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jipiboily/monologue/issues/255#issuecomment-96041133>.
>



-- 
John Cox
*MACH19*
mach19.com
303-647-1357

**Comment by johncox00** [comment]
Private repo..tread lightly. Thanks for taking a look!

**Comment by msevestre** [comment]
cool. Please let me know which repo I should be looking at.
Thanks

**Comment by johncox00** [comment]
Should be jnj. Rails app with spree mounted at /store and monologue mounted
at /blog. the `blog` branch is where I was last playing with monologue.

On Fri, Apr 24, 2015 at 2:14 PM, Michael Sevestre <notifications@github.com>
wrote:

> cool. Please let me know which repo I should be looking at.
> Thanks
>
> On Fri, Apr 24, 2015 at 4:00 PM, John Cox <notifications@github.com>
> wrote:
>
> > Private repo..tread lightly. Thanks for taking a look!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jipiboily/monologue/issues/255#issuecomment-96047038
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jipiboily/monologue/issues/255#issuecomment-96051687>.
>



-- 
John Cox
*MACH19*
mach19.com
303-647-1357

**Comment by msevestre** [comment]
You sure I have access to this repo? Can't seem to find it....

**Comment by johncox00** [comment]
Now you do. Added the team but didn't associate it with the repo. 

______________________
John Cox
303-647-1357

**Comment by msevestre** [comment]
You are using another layout (spree one as far as I can tell)

You need the
<%= render 'layouts/monologue/application/sidebar' %> somewhere in your
layout

I am on my phone now so sorry if I am mistaken.... :-)

**Comment by johncox00** [comment]
That should take care of it for me. Thank you!

______________________
John Cox
303-647-1357

**Comment by msevestre** [comment]
Closing the issue. Please reopen if you need
