### ISSUE TITLE
How to integrate Monologue with pre-existing auth system?

### ISSUE THREAD

**Issue by CryptoSnippets** [jipiboily/monologue#260]
Hi,

Is there any documentation or tutorial available explaining how to integrate Monologue with a host application's pre-existing authentication system?

In my setup only the admin user should be able to blog.

Thanks for any help.

**Comment by FromUte** [comment]
Would love the same info !

**Comment by msevestre** [comment]
there is no documentation as far as I can tell. You would have to monkey patch the user in monologue to use your own system.

Check that out
https://gist.github.com/jipiboily/776d907fc932640ac59a
