### ISSUE TITLE
Monologue and AWS S3

### ISSUE THREAD

**Issue by kyle-annen** [jipiboily/monologue#262]
I was wondering how to go about configuring Monologue to use S3?  Everything is fully functional deployed on Heroku in conjunction with my main_app, mounted as an engine.  However image uploads are non-functioning.  I am assuming Paperclip is not utilized for uploads?

**Comment by msevestre** [comment]
You could use the monologue image extensions and configure it to your need?

**Comment by msevestre** [comment]
thtps://github.com/msevestre/monologue_image_upload
