### ISSUE TITLE
Can't over ride fonts

### ISSUE THREAD

**Issue by TheNickHurst** [jipiboily/monologue#263]
The main part of my site is built with the materialize css framework, so I'd like the fonts on the blog to be consistent with the rest of the site (i.e. Roboto).

In my app/stylesheets/monologue/blog/fonts.css I have:

    @import url(http://fonts.googleapis.com/css?family=Roboto:400,900,700italic,900italic,700,500italic,500,400italic,300,300italic);

    * {
        font-family: 'Roboto', Arial, sans-serif !important;
    }

And all the fonts are the default, serif-fonts and arial. Is there something I'm not doing correctly? And if for some reason you can't override those fonts, could that be made possible?

**Comment by msevestre** [comment]
you can override the fonts and the whole css for that matter. ensure that the css is loaded properly and that it's being used in the application as expected
