### ISSUE TITLE
Could not find generator monologue:views

### ISSUE THREAD

**Issue by sengenbe** [jipiboily/monologue#266]
Trying to change the views without success.  

I've tried: 
rails g monologue:views
rails g monologue:views blog

and for each I'm receiving the error in the title.

My scope is:
mount Monologue::Engine, at: '/blog'

**Comment by msevestre** [comment]
Which version are you using? Generator are only available on master

**Comment by sengenbe** [comment]
I'm on master.  I ended up copying them over manually but figured I'd open an issue in case it's a problem others have.

**Comment by ffigueroa** [comment]
I have the same issue :(

**Comment by msevestre** [comment]
Ok I merged a PR without testing it before and most likely it was a
mistake. Can one of you look at that an submit a PR? That would be very
cool. Thanks guys

**Comment by sengenbe** [comment]
Sorry, just realizing I didn't reply here - do you need anything on this still?

**Comment by msevestre** [comment]
Yes.  Apparently it's  not working. ....I have no time to look at that at
the moment

**Comment by katawura** [comment]
Getting the same error. Is there any chance that you can point us to the right direction to help us resolve this, its an amazing blog engine but need a bit of control over the views to help develop to suit designs.

**Comment by msevestre** [comment]
I will look at that tomorrow  and see if I can find a solution.  Will keep
you posted

**Comment by katawura** [comment]
Yeah pelase, that would be awesome! thanks

**Comment by msevestre** [comment]
All right guys. I have just created a brand new rails 4.2 app and mounted monologue from master under /blog using `mount Monologue::Engine, at: '/blog'`
I could without any problem generates the view. By default however they were generated under a subfolder monologue which did not work for me so I changed that behavior

Can you make sure that you are using the latest master? What do you see when you type rails g?
Please let me know.
Thanks

**Comment by katawura** [comment]
It worked for me thanks. 

In my gem files l had gem 'monologue', :git => 'https://github.com/jipiboily/monologue.git'

and got whats below on running rails g

eneral options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

Rails:
  assets
  controller
  generator
  helper
  integration_test
  jbuilder
  job
  mailer
  migration
  model
  resource
  responders_controller
  scaffold
  scaffold_controller
  task

ActiveRecord:
  active_record:devise

Ckeditor:
  ckeditor:install
  ckeditor:pundit_policy

Coffee:
  coffee:assets

Devise:
  devise
  devise:controllers
  devise:install
  devise:views

Js:
  js:assets

Mongoid:
  mongoid:devise

Monologue:
  monologue:views

Responders:
  responders:install

TestUnit:
  test_unit:generator
  test_unit:job
  test_unit:plugin

Uploader:
  uploader

so was pretty confident it would so went ahead with rails g monologue:views and worked :)
Thanks @msevestre

**Comment by msevestre** [comment]
awesome. Thanks for your feedback Kelvin

**Comment by sengenbe** [comment]
We ended up building what we needed, but I was just using:

gem 'monologue'    monologue (0.4.1)
