### ISSUE TITLE
Is there a config to remove the article posted date from URL?

### ISSUE THREAD

**Issue by sengenbe** [jipiboily/monologue#267]
Curious if there's a config setting for this.  I'm using monologue for articles rather than a blog (date driven) structure.  Thanks!

**Comment by msevestre** [comment]
There isn't. You can simply override the one partial that displays the post
header or use deface to remove the one element from the html

**Comment by sengenbe** [comment]
I actually meant the path (blog/2015/) which I now see is a field in the edit post! ::shameface::
