### ISSUE TITLE
Can multiple instances be installed?

### ISSUE THREAD

**Issue by sengenbe** [jipiboily/monologue#269]
Hi guys,
I have a two sided marketplace application where there are two distinct user types.  I did a basic install at /blog but ultimately would like to have two instances (one at /some-user-blog/ and another at /other-users-blog/) so that they have their own index pages.  Is this possible with monologue now?  I realize the ask is likely a corner case but worth a shot!  Thanks

**Comment by jipiboily** [comment]
Hey @sengenbe. Not 100% sure, but I would say no....what do you think @msevestre? Kinda rusty on Rails Engines... :)

**Comment by msevestre** [comment]
I would say no as well but might be worth a try... And let us know
