### ISSUE TITLE
The bcrypt-ruby gem has changed its name to just bcrypt.

### ISSUE THREAD

**Issue by hassanakram** [jipiboily/monologue#270]
I see the following note after I added `monologue` gem into my Gemfile. 

**The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your dependencies accordingly.**

**Comment by msevestre** [comment]
which version of monologue are you using?

**Comment by msevestre** [comment]
that's the dependency that we have now
` s.add_dependency "bcrypt", '~> 3.1.7'` so we are using bcrypt

**Comment by msevestre** [comment]
closing issue. Please reopen if you are using master
