### ISSUE TITLE
Question - Show latest post on another view

### ISSUE THREAD

**Issue by flxkrmr** [jipiboily/monologue#273]
I have mounted my monologue blog under "/mono" and want to show the latest post (or a preview) on my main page under "/".
Is there an easy way to access the monologue posts from another view or controller?

**Comment by flxkrmr** [comment]
Oh sorry, I just realized there is a mailing list for questions..

**Comment by parasharrk** [comment]
@flxkrmr why don't you paste the URL of mailing list here, and then we can ask to close this issue.

**Comment by msevestre** [comment]
Thanks
