### ISSUE TITLE
Version 0.5

### ISSUE THREAD

**Issue by msevestre** [jipiboily/monologue#275]
Well I think it's miee than about time for a new version and I have a few hours next week that I am going to use to push a new gem. Any concerns anyone?

**Comment by jipiboily** [comment]
Yes please! :) (no concerns at all!)

  

<br  
Jean-Philippe Boily  
Founder @ Metrics Watch | <http://metrics.watch/>  
Freelancer | <http://jipiboily.com/hire-me/> (web apps developer, part-
time/interim CTO and help for startups)

> On Dec 4 2015, at 8:00 pm, Michael Sevestre &lt;notifications@github.com&gt;
wrote:  

>

> Well I think it's miee than about time for a new version and I have a few
hours next week that I am going to use to push a new gem. Any concerns anyone?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/jipiboi
ly/monologue/issues/275).![](https://github.com/notifications/beacon
/AAOOITlVJ-APaFID8fo1Rfz5vVpfC6tBks5pMi62gaJpZM4GvTll.gif)

**Comment by msevestre** [comment]
done! Version 0.5.0 is out (0.5.0 tag created, 0-5-stable branch created and gem published)
