### ISSUE TITLE
Cannot change admin layout

### ISSUE THREAD

**Issue by codeundercoverdev** [jipiboily/monologue#278]
My routes file:

    mount Monologue::Engine, at: '/blog'

In monologue.rb config file:

    config.layout               = "blog/layouts/monologue/application"

I can change the main blog but I can't change the admin screen.  I've added a biography attribute to the monologue_users table and I need it to show up for the new user form, but since all the layout changes I make have zero effect and don't show up at all in the browser, I can't.  How do I make changes to the monologue admin section?

**Comment by jipiboily** [comment]
What you want to do if I understand well is not to change the layout but add a field to the user admin form, right? If this is the case, just overwrite https://github.com/jipiboily/monologue/blob/master/app/views/monologue/admin/users/_form.html.erb using a file with the exact same file name and exact same path (`app/views/monologue/admin/users/_form.html.erb`) in your project and your own view will be loaded.

Hope that helps, if not, feel free to re-open.

**Comment by codeundercoverdev** [comment]
Thanks, that is what I am trying to do, but editing the _form file has no effect on the layout.  Nothing changes.  That's the issue.

I am trying to reopen the issue but github won't let me.

**Comment by jipiboily** [comment]
Did you make a copy of the `_form.html.erb` in your own project, at the same path with the same file name?

**Comment by codeundercoverdev** [comment]
Yes, I did.  Changing the file has no effect, nor do any changes i make to the application.html.erb file (although they do change the main blog, just not the admin area).

**Comment by jipiboily** [comment]
Two questions:
- Which version of Monologue and Rails are you using?
- Is the project public or do you have a public way to reproduce this?

I'm 99% sure there must be a different path, could be a typo...I did that so many times... :grinning:

**Comment by codeundercoverdev** [comment]
Thanks for your help.  I'm not sure what happened, because I changed nothing since making this post (my git just proved that to me) but now it works for some reason.

**Comment by jipiboily** [comment]
:+1:

**Comment by jipiboily** [comment]
Could have been a dev caching issue with Rails...glad it works!
