### ISSUE TITLE
strong parameters 

### ISSUE THREAD

**Issue by codeundercoverdev** [jipiboily/monologue#279]
I just added a :bio attribute to the Monologue_users table, but :bio is an unpermitted parameter.  Is there a way of permitting the parameter without overwriting/rewriting the entire controller?

**Comment by jipiboily** [comment]
I don't think so...well, you don't need to overwrite the whole controller, but to re-open it's definition. In an initializer, you can try:

```ruby
class Monologue::Admin::UsersController
  private
  def user_params
    # your code
  end
end
```

**Comment by jipiboily** [comment]
If that doesn't work, you can try a `class_eval`.

**Comment by codeundercoverdev** [comment]
class_eval worked.  Final code in case it can help anyone:

    Monologue::Admin::UsersController.class_eval do
      private
      def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation, :bio)
      end
    end
Thanks @jipiboily

**Comment by jipiboily** [comment]
Gladly.
