### ISSUE TITLE
Skip devise authenticate_user!

### ISSUE THREAD

**Issue by Pete-Tyldesley** [jipiboily/monologue#281]
Hi, I'm using this gem with devise and loving it! Great work! Only trouble is I have it set up with devise, where I'm using the authenticate_user! method. I want the blog to be accessible to anyone, so is there a way for me to skip the before_action for the blog?

**Comment by Pete-Tyldesley** [comment]
Never mind, I solved the problem by adding this to config/application.rb:

`config.to_prepare do
        Monologue::ApplicationController.skip_before_filter :authenticate_user!
    end`

**Comment by msevestre** [comment]
excellent.
So your goal is to have everyone access the admin section?

**Comment by jipiboily** [comment]
My understanding is that he has Devise setup in the main app and don't want it to interfere with Monologue public pages...?

**Comment by Pete-Tyldesley** [comment]
Yeah, that's exactly right. Users need to log in to use the main app but I want them to be able to access the blog without needing to sign up. It doesn't seem to have interfered with the admin section as you still have to log in to monologue to use the admin section.
