### ISSUE TITLE
Browse server on new post for images doesnt work

### ISSUE THREAD

**Issue by morais17** [jipiboily/monologue#284]
Hello there, im trying to use monologue on my new app and everything works perfectly minus the browse server thing. Every time i press the button it opens a popup with a 404 page (wich basically says that the page doesnt exist). 

Is there anything i have to configure for this to work?

**Comment by morais17** [comment]
`Started GET "/ckeditor/pictures?CKEditor=post_content&CKEditorFuncNum=1&langCode=en" for 127.0.0.1 at 2016-03-01 20:48:01 +0000
Processing by Monologue::PostsController#show as HTML
  Parameters: {"CKEditor"=>"post_content", "CKEditorFuncNum"=>"1", "langCode"=>"en", "post_url"=>"ckeditor/pictures"}
  Monologue::Tag Load (0.4ms)  SELECT `monologue_tags`.* FROM `monologue_tags`  ORDER BY name
   (0.6ms)  SELECT COUNT(*) FROM `monologue_posts` INNER JOIN `monologue_taggings` ON `monologue_posts`.`id` = `monologue_taggings`.`post_id` WHERE `monologue_taggings`.`tag_id` = 2 AND `monologue_posts`.`published` = 1 AND (published_at <= '2016-03-01 20:48:01.942711')
   (0.5ms)  SELECT COUNT(*) FROM `monologue_posts` INNER JOIN `monologue_taggings` ON `monologue_posts`.`id` = `monologue_taggings`.`post_id` WHERE `monologue_taggings`.`tag_id` = 1 AND `monologue_posts`.`published` = 1 AND (published_at <= '2016-03-01 20:48:01.946315')
   (0.5ms)  SELECT COUNT(*) FROM `monologue_posts` INNER JOIN `monologue_taggings` ON `monologue_posts`.`id` = `monologue_taggings`.`post_id` WHERE `monologue_taggings`.`tag_id` = 2 AND `monologue_posts`.`published` = 1 AND (published_at <= '2016-03-01 20:48:01.948768')
   (0.5ms)  SELECT COUNT(*) FROM `monologue_posts` INNER JOIN `monologue_taggings` ON `monologue_posts`.`id` = `monologue_taggings`.`post_id` WHERE `monologue_taggings`.`tag_id` = 1 AND `monologue_posts`.`published` = 1 AND (published_at <= '2016-03-01 20:48:01.951283')
   (0.5ms)  SELECT COUNT(*) FROM `monologue_posts` INNER JOIN `monologue_taggings` ON `monologue_posts`.`id` = `monologue_taggings`.`post_id` WHERE `monologue_taggings`.`tag_id` = 2 AND `monologue_posts`.`published` = 1 AND (published_at <= '2016-03-01 20:48:01.957460')
   (0.5ms)  SELECT COUNT(*) FROM `monologue_posts` INNER JOIN `monologue_taggings` ON `monologue_posts`.`id` = `monologue_taggings`.`post_id` WHERE `monologue_taggings`.`tag_id` = 1 AND `monologue_posts`.`published` = 1 AND (published_at <= '2016-03-01 20:48:01.960323')
  Monologue::Post Load (0.4ms)  SELECT  `monologue_posts`.* FROM `monologue_posts` WHERE `monologue_posts`.`published` = 1 AND (published_at <= '2016-03-01 20:48:01.962782')  ORDER BY published_at DESC, monologue_posts.created_at DESC, monologue_posts.updated_at DESC LIMIT 100
  Monologue::Tagging Load (0.4ms)  SELECT `monologue_taggings`.* FROM `monologue_taggings` WHERE `monologue_taggings`.`post_id` IN (2)
  Monologue::Tag Load (0.3ms)  SELECT `monologue_tags`.* FROM `monologue_tags` WHERE `monologue_tags`.`id` IN (2, 1)  ORDER BY id ASC
  Monologue::User Load (0.3ms)  SELECT  `monologue_users`.* FROM `monologue_users` WHERE `monologue_users`.`id` = 1 LIMIT 1
  Monologue::Post Load (0.3ms)  SELECT  `monologue_posts`.* FROM `monologue_posts` WHERE (url = 'ckeditor/pictures')  ORDER BY published_at DESC, monologue_posts.created_at DESC, monologue_posts.updated_at DESC LIMIT 1
  Rendered public/404.html (0.6ms)
Completed 404 Not Found in 39ms (Views: 4.5ms | ActiveRecord: 5.2ms)
`

**Comment by msevestre** [comment]
Image is not implemented by default. You will need to use the
monologue_image extension

**Comment by morais17** [comment]
Yeah i used it. I can upload images to my blog and they are saved on the app. I just can´t use whatever the "Browse Server" does. I think that it is to choose an image already saved on the app, but it always does a 404

**Comment by msevestre** [comment]
Hum....not sure about that then....maybe there are some settings to set so
that ckeditor knows where to look?

**Comment by morais17** [comment]
I don't know where though, It even works with a url. Just the browse server that doesnt work. But i've looked everywhere and nothing :/

**Comment by morais17** [comment]
Changing the url from / to /blog fixed so i guess it was a problem with the url yeah

**Comment by jipiboily** [comment]
So I guess this can be closed? Also, it was posted on the wrong project as I understand?

Feel free top re-open if I'm wrong :)
