### ISSUE TITLE
Disable Disqus comments

### ISSUE THREAD

**Issue by lioneljingles** [jipiboily/monologue#285]
How do I disable Disqus comments entirely? Leaving the Disqus without configuration results in a javascript error:

    GET http://.disqus.com/embed.js net::ERR_NAME_NOT_RESOLVED

**Comment by jipiboily** [comment]
I don't think there is any option for that. You could overwrite the disqu partial, at the exact same path in your app, with an empty file.

**Comment by jipiboily** [comment]
There are two, can't remember which one is which, but worst case overwrite both or look in the code to see which one is the one you want.

https://github.com/jipiboily/monologue/blob/master/app/views/layouts/monologue/application/_disqus.html.erb
https://github.com/jipiboily/monologue/blob/master/app/views/layouts/monologue/application/_disqus_embed.html.erb

Feel free to reopen if it doesn't work, or send a PR adding an option for it.

**Comment by lioneljingles** [comment]
The second one worked! Thank you!!
