### ISSUE TITLE
Remove like/+1 buttons at bottom of post

### ISSUE THREAD

**Issue by nitinsavant** [jipiboily/monologue#286]
At the bottom of an individual post, it says: "Loved what you just read? Share it!" 

How can I remove this text and the share icons from every post?

**Comment by jipiboily** [comment]
Overwrite [this file](https://github.com/jipiboily/monologue/blob/master/app/views/monologue/posts/_social_sharing.html.erb) at the exact same location in your project with a blank file and you should be good.

**Comment by nitinsavant** [comment]
That definitely works. Another option (that I went with) is to comment the line below from the "show.html.erb" file.

`<%= render "monologue/posts/social_sharing" %>`

**Comment by jipiboily** [comment]
Yup, I didn't know you already had it, and I prefer to overwrite the least amount of things possible to be future proof, even if Monologue is not changing so much.

**Comment by nitinsavant** [comment]
Gotcha. I was actually wondering why I wouldn't just overwrite everything initially but now I realize that it's because I just installed Monologue and haven't had to deal with upgrades. Good to know. Thanks again.
