### ISSUE TITLE
How to remove the lines above and below a post header?

### ISSUE THREAD

**Issue by nitinsavant** [jipiboily/monologue#287]
There are lines above and below each post header. I'd like to remove the line above and remove the line below?

**Comment by jipiboily** [comment]
Can you be more explicit, or maybe share a screenshot or code sample? It's been a long time, and I don't know exactly what you are talking about... 😕

**Comment by nitinsavant** [comment]
Of course. Here you go: https://www.dropbox.com/s/ps3d1lc4913q784/Screenshot%202016-04-12%2015.52.35.png?dl=0

**Comment by jipiboily** [comment]
I would probably just hide them, with CSS...look at https://github.com/jipiboily/monologue/wiki/Customizations on how to do that.

**Comment by nitinsavant** [comment]
Correct. My real issue is that I didn't know which CSS selector to override. After looking through the monologue source, specifically the monologue.css file, I added the CSS below to my project's custom.css file  to get what I wanted: 

.content header {
  border-top: none;
}
