### ISSUE TITLE
How can I resolve this warning: "Post saved: posts with a future publication date ..."

### ISSUE THREAD

**Issue by phanviet** [jipiboily/monologue#290]
> Post saved: posts with a future publication date will not be shown unless cache is cleared on that same day. Cache will most probably be generated before that and won't be refreshed automatically.

How can I resolve above message in admin page without disable cache? Could it wipe cache auto?

**Comment by jipiboily** [comment]
You would have to develop something by yourself. If I recall correctly, this is just generating static files by default, so you can just have a cron job clearing it every at midnight, or every hour or something like that.

You could also develop something fully in Ruby, using https://github.com/tomykaira/clockwork to trigger the cache clearing.

Hope that helps!
