### ISSUE TITLE
Upgrade Capybara

### ISSUE THREAD

**Issue by illegalnumbers** [jipiboily/monologue#305]
Capybara is at a very old version and should be upgraded. This will break many tests. I tried a brief upgrade but some of the things that the tests were doing I couldn't fix, namely window switching to the new window switching API and you'll need to add in some id's on content to find them.

**Comment by jipiboily** [comment]
Yeah, a lot of broken things. Sorry about that. Trying to get back on track. Paying $100 to anyone who puts Monologue back on track with Rails 5 support. Closing but see https://github.com/jipiboily/monologue/issues/314

**Comment by illegalnumbers** [comment]
I am easily bought with $100.

**Comment by jipiboily** [comment]
@illegalnumbers hehe :)

Does that mean you want to give it a shot and "make Monologue great again" and make it work with Rails 5 and all that jazz? Would be awesome!

**Comment by illegalnumbers** [comment]
I will see if I can find some time. Unfortunately it seems my promises these days to do side coding tend to be for naught so I avoid all promises now.

**Comment by jipiboily** [comment]
Sure, no worry :)

Just post here if you do start the work, to avoid someone else to start it at the same time.

Thanks!

**Comment by jipiboily** [comment]
Well, not here but in #314 in fact.
