### ISSUE TITLE
Upgrade RSpec

### ISSUE THREAD

**Issue by illegalnumbers** [jipiboily/monologue#306]
RSpec is at a very outdated version and should be upgraded.

**Comment by msevestre** [comment]
Can you submit a PR for that?

**Comment by jipiboily** [comment]
Yeah, a lot of broken things. Sorry about that. Trying to get back on track. Paying $100 to anyone who puts Monologue back on track with Rails 5 support. Closing but see https://github.com/jipiboily/monologue/issues/314
