### ISSUE TITLE
Twitter feed not working - SOLVED - please incorporate solution

### ISSUE THREAD

**Issue by RWSDev** [jipiboily/monologue#309]
if anyone wants to add twitter support just replace:
`<script type="text/javascript" src="https://api.twitter.com/1/statuses/user_timeline/<%= Monologue::Config.twitter_username %>.json?callback=TwitterWidget.callback&amp;count=5"></script>
`
with:
`<a class="twitter-timeline" data-tweet-limit="3" href="https://twitter.com/<%= Monologue::Config.twitter_username %>">Tweets by <%= Monologue::Config.twitter_username %></a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by jipiboily** [comment]
Thanks for pointing that out. If you send a PR I will gladly merge it. Thanks!

**Comment by ptylde** [comment]
Sent the PR for this fix.
