### ISSUE TITLE
ButterCMS sponsorship?

### ISSUE THREAD

**Issue by msevestre** [jipiboily/monologue#313]
@jipiboily 
Did you authorize that?
https://github.com/jipiboily/monologue/commit/e418a877100e4443f497857c08a6ce1c5db2f7a0

**Comment by msevestre** [comment]
This is actually kind of crazy to advertise here for another blog engine. 
Unless there is a good reason, I am going to remove it

**Comment by jipiboily** [comment]
I did authorize that. Happy to chat about it anytime :)

**Comment by msevestre** [comment]
Well yes. Send me an email in private to let me know why that is and how
this can benefit monologue
