### ISSUE TITLE
Error when running migration generator

### ISSUE THREAD

**Issue by flrnt** [jipiboily/monologue#316]
Get stuck with an error after running `bin/rake monologue:install:migrations`

```bash
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:238:in `add_request_method': You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action" (ArgumentError)
...
```
I then test my `routes.rb` file with only this (avoiding potential error with match method : 
```rb
Rails.application.routes.draw do
  # blog
  mount Monologue::Engine, at: '/'
end
```
But occurs the same error. Any idea ?

**Comment by flrnt** [comment]
EDIT : after some research, made a fork of repo and update my dependencies. Works fine !

**Comment by msevestre** [comment]
what did you have to update? could you submit a PR?

**Comment by flrnt** [comment]
I red this issue #232, made a fork and update some gems. But had another issue with monologue.rb and config.sidebar, like `@tasks`is nil then can't iterate on it. This variable isn't in the Monologue::PostsController#index action, fixed it, but had another issue, then I give up to another blog engine :(
