### ISSUE TITLE
Work on integration with apps using Devise

### ISSUE THREAD

**Issue by jipiboily** [jipiboily/monologue#56]
Make it easy to make Monologue work flawlessly with applications using Devise.

From @tmancino: "_Only issue encountered was in trying to use current_user.user_name method call with Devise on the main_app. It looks like it is conflicting with the monologue current_user helper method in the overridden view._"

https://github.com/jipiboily/monologue/issues/54#issuecomment-5718418

**Comment by CryptoSnippets** [comment]
@Fire-Dragon-DoL did you find a solution to the double login issue?

**Comment by Fire-Dragon-DoL** [comment]
@CryptoSnippets Nope, sorry, had to make it from scratch by myself (news creation)

**Comment by msevestre** [comment]
Extracting auth should be fairly simple. If anyone is up for that I would
be happy to review the code

**Comment by MicFin** [comment]
Is something like this a good start for the core team to look at? 
http://www.ixlan.net/blog/2014/monologue-device-rails-gems-one-table

(I'm a first time user of Monologue, so far so good but I also have run into the need for Devise user login)

**Comment by msevestre** [comment]
looking good!
